---

development:
  url: <%= ENV['DATABASE_URL'] || 'postgres://root:root@db/ucbears-dev?pool=5' %>

test:
  url: <%= ENV['DATABASE_URL'] ||'postgres://root:root@db/ucbears-test?pool=5' %>

production:
  url: <%= ENV['DATABASE_URL'] || 'postgres://root:root@db/ucbears-prod' %>
