inherit_from: ../.rubocop.yml

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

############################################################
# rubocop-rails

# we meant to do that
Rails/SkipsModelValidations:
  Enabled: false

# we meant to do that
Rails/TimeZone:
  Enabled: false
