inherit_from: ../.rubocop.yml




############################################################
# rubocop-rails

# This is used as plain Ruby not ActiveRecord. Pluck not available
# in the context used
Rails/Pluck:
  Enabled: false